### ISSUE TITLE
Why use different storage for weights and times?

### ISSUE THREAD

**Issue by gdalle** [davidfang00/Julia_Hashcode2014.jl#11]
https://github.com/davidfang00/Julia_Hashcode2014.jl/blob/4d67fe219b275b648f3193f119b93d4f453e22a0/src/adjacency_matrix.jl#L14

**Comment by davidfang00** [comment]
The weights are currently a vector, ordered by the largest distance to smallest distance. This is a choice we made because in our original greedy method, we randomly sample from the largest few junctions, so it can take advantage of this pre-sorted storage method. Our later algorithms do not take advantage of this however, and could so the storage methods could be changed to be identical. Thankfully, we abstract the accessors so it wouldn't be too difficult to change.

**Comment by gdalle** [comment]
You do as you please, I just wanted to point it out :)
